# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/task-tracker',
                'doc_host': 'https://KonKob.github.io',
                'git_url': 'https://github.com/KonKob/task-tracker',
                'lib_path': 'task_tracker'},
  'syms': {'task_tracker.core': {'task_tracker.core.foo': ('core.html#foo', 'task_tracker/core.py')}}}
